title: My Test Blog
author: Enmiligi
description: > # this means to ignore newlines until "baseurl:"
  This is my test Blog made with the Course
  https://lab.github.com/githubtraining/github-pages
  of the Github Learning Lab

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
